# Generated by Django 4.1.1 on 2022-10-13 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_d',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='service',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
