# Generated by Django 4.1.1 on 2022-10-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_service_total_d_service_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(choices=[('Swimming Pool', 'Swimming Pool'), ('Picnic Spot', 'Picnic Spot'), ('Community Hall', 'Community Hall')], default='Select', max_length=50),
        ),
    ]
