# Generated by Django 4.1.1 on 2022-10-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
